name: ReleaseCI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Release to S3
      run: bash scripts/pipeline/release.sh ${{secrets.BUCKET_NAME}} "ADS/src" ${{secrets.AWS_ACCESS_KEY}} ${{secrets.AWS_SECRET_KEY}} "src"